version: 2.0
jobs:

  build:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Yarn
          command: yarn --pure-lockfile --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build-n-test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore:
                - /.*/
      - test:
          requires:
            - build
